[project]
name = "helion-layernorm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "helion>=0.2.1",
    "numpy>=2.3.4",
    "pytest>=8.4.2",
    "torch>=2.9.0",
    "triton>=3.5.0",
]
